Torna o init script um pouco mais robusto

diff --git a/modules/pje/templates/initscript.erb b/modules/pje/templates/initscript.erb
--- a/modules/pje/templates/initscript.erb
+++ b/modules/pje/templates/initscript.erb
@@ -6,24 +6,30 @@ SCRIPT1GRAU=<%= scope['::pje::params::jboss_home'] %>/bin/pje-1grau-default.sh
 SCRIPT2GRAU=<%= scope['::pje::params::jboss_home'] %>/bin/pje-2grau-default.sh
 
 if [[ $# -eq 0  ]]; then
-	echo "Usage: $0 {start|stop|restart|kill|status} <1grau|2grau>"
-	exit 1
+    echo "Usage: $0 {start|stop|restart|kill|status} <1grau|2grau>"
+    exit 1
 
 elif [[ $# -eq 1 ]]; then
-	$SCRIPT1GRAU "$1"
-	[[ "$1" = "start" ]] && sleep 30s
-	$SCRIPT2GRAU "$1"
+  [[ -x $SCRIPT1GRAU ]] && $SCRIPT1GRAU "$1" || \
+    echo "PJE '1grau' instance is not ready and will be not started" \
+    exit 2
+
+  #[[ "$1" = "start" ]] && sleep 30s
+
+  [[ -x $SCRIPT2GRAU ]] && $SCRIPT2GRAU "$1" || \
+    echo "PJE '2grau' instance is not ready and will be not started" \
+    exit 2
 
 elif [[ $# -ge 2 ]]; then
-	if [[ "$2" = "1grau" ]]; then
-		$SCRIPT1GRAU "$1"
-	
-	elif [[ "$2" = "2grau" ]]; then
-		$SCRIPT2GRAU "$1"
-	
-	else
-		echo "PJE '$2' is an invalid instance"
-		exit 1
+    if [[ "$2" = "1grau" ]]; then
+        [[ -x $SCRIPT1GRAU ]] && $SCRIPT1GRAU "$1"
+    
+    elif [[ "$2" = "2grau" ]]; then
+        [[ -x $SCRIPT2GRAU ]] && $SCRIPT2GRAU "$1"
+    
+    else
+        echo "PJE '$2' is an invalid instance"
+        exit 3
 
-	fi
+    fi
 fi
